name: Comment
on: pull_request
jobs:
  commnet:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - run: gh pr coment "${GITHUB_HEAD_REF}" --body "HELLO apeiria, ${GITHUB_ACTOR}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
